param(
  [string]$CsvPath = "data/source/charts.csv",
  [string]$OutPath = "docs/data-audit.md"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $CsvPath)) {
  throw "CSV not found: $CsvPath"
}

$rows = Import-Csv -LiteralPath $CsvPath
$columns = @()
if ($rows.Count -gt 0) {
  $columns = $rows[0].PSObject.Properties.Name
}

$requiredColumns = @("name", "name_kr", "artist", "label", "type", "level", "bg_img")
$targetPools = @("S16", "S17", "S18", "S19", "S20", "S21", "S22", "D23")

function Normalize-Type([object]$value) {
  $text = ([string]$value).Trim().ToUpperInvariant()
  if ($text.StartsWith("S")) { return "S" }
  if ($text.StartsWith("D")) { return "D" }
  return $text
}

function Normalize-Level([object]$value) {
  $text = ([string]$value).Trim()
  $match = [regex]::Match($text, "\d+")
  if ($match.Success) { return $match.Value }
  return $text
}

$poolCounts = [ordered]@{}
foreach ($pool in $targetPools) {
  $poolType = $pool.Substring(0, 1)
  $poolLevel = $pool.Substring(1)
  $poolCounts[$pool] = @($rows | Where-Object {
    (Normalize-Type $_.type) -eq $poolType -and (Normalize-Level $_.level) -eq $poolLevel
  }).Count
}

$bgPopulated = @($rows | Where-Object { -not [string]::IsNullOrWhiteSpace([string]$_.bg_img) }).Count
$bgMissing = @($rows | Where-Object { [string]::IsNullOrWhiteSpace([string]$_.bg_img) }).Count

$missingCounts = [ordered]@{}
foreach ($field in @("name", "artist", "type", "level", "bg_img")) {
  $missingCounts[$field] = @($rows | Where-Object { [string]::IsNullOrWhiteSpace([string]$_.($field)) }).Count
}

$duplicateGroups = $rows |
  Group-Object {
    "{0}|{1}|{2}|{3}" -f
      ([string]$_.name).Trim().ToLowerInvariant(),
      ([string]$_.artist).Trim().ToLowerInvariant(),
      (Normalize-Type $_.type),
      (Normalize-Level $_.level)
  } |
  Where-Object { $_.Count -gt 1 -and $_.Name -ne "|||" } |
  Sort-Object Count -Descending

$typeValues = $rows | Group-Object type | Sort-Object Count -Descending
$nonCanonicalTypeValues = $typeValues | Where-Object {
  $value = ([string]$_.Name).Trim().ToLowerInvariant()
  $value -notin @("s", "d", "c")
}
$levelValues = $rows | Group-Object level | Sort-Object Name
$nonNumericLevelValues = $levelValues | Where-Object {
  $normalized = Normalize-Level $_.Name
  -not [regex]::IsMatch($normalized, "^\d+$")
}

$poolLines = foreach ($pool in $targetPools) {
  $status = if ($poolCounts[$pool] -ge 7) { "PASS" } else { "FAIL" }
  "- ${pool}: $($poolCounts[$pool]) ($status)"
}

$missingColumnLines = foreach ($col in $requiredColumns) {
  $status = if ($columns -contains $col) { "PASS" } else { "FAIL" }
  "- ${col}: $status"
}

$missingFieldLines = foreach ($key in $missingCounts.Keys) {
  "- ${key}: $($missingCounts[$key])"
}

$duplicateLines = if ($duplicateGroups.Count -eq 0) {
  @("- No duplicate chart keys found using name + artist + type + level.")
} else {
  $duplicateGroups | Select-Object -First 20 | ForEach-Object {
    $sample = $_.Group[0]
    "- $($sample.name) / $($sample.artist) / $($sample.type) / $($sample.level): $($_.Count) rows"
  }
}

$typeLines = $typeValues | ForEach-Object { "- $($_.Name): $($_.Count)" }
$nonCanonicalTypeLines = if ($nonCanonicalTypeValues.Count -eq 0) {
  @("- None found.")
} else {
  $nonCanonicalTypeValues | ForEach-Object { "- $($_.Name): $($_.Count)" }
}
$levelLines = $levelValues | ForEach-Object { "- $($_.Name): $($_.Count)" }
$nonNumericLevelLines = if ($nonNumericLevelValues.Count -eq 0) {
  @("- None found.")
} else {
  $nonNumericLevelValues | ForEach-Object { "- $($_.Name): $($_.Count)" }
}

$allPoolsPass = -not ($targetPools | Where-Object { $poolCounts[$_] -lt 7 })
$requiredColumnsPass = -not ($requiredColumns | Where-Object { $columns -notcontains $_ })
$bgPercent = if ($rows.Count -eq 0) { 0 } else { [math]::Round(($bgPopulated / $rows.Count) * 100, 2) }

$report = @"
# Data Audit

Generated by `scripts/write-data-audit.ps1`.

## Source

- CSV path: $CsvPath
- Total rows: $($rows.Count)

## Detected Columns

$(($columns | ForEach-Object { "- $_" }) -join "`n")

## Required Columns

$($missingColumnLines -join "`n")

Required column status: $(if ($requiredColumnsPass) { "PASS" } else { "FAIL" })

## Required Pool Counts

$($poolLines -join "`n")

Required pool status: $(if ($allPoolsPass) { "PASS - every required pool has at least 7 charts." } else { "FAIL - at least one required pool has fewer than 7 charts." })

## Type Distribution

$($typeLines -join "`n")

## Non-Canonical Type Values

$($nonCanonicalTypeLines -join "`n")

## Level Distribution

$($levelLines -join "`n")

## Non-Numeric Level Values

$($nonNumericLevelLines -join "`n")

## Background Image Population

- Populated bg_img: $bgPopulated
- Missing bg_img: $bgMissing
- Population rate: $bgPercent%

## Missing Required Values

$($missingFieldLines -join "`n")

## Duplicate Chart Keys

$($duplicateLines -join "`n")

## Phase 3 Risks

- bg_img values should be cached locally or moved to controlled storage before event day.
- Any chart image fetch failures need a fallback title-card render path.
- Song-key derivation must avoid blocking separate charts unnecessarily while still preventing same-song repeats.
- Chart exclusions can reduce pool size; Phase 3 should validate post-exclusion pools still have at least 7 eligible charts.
- The audit found non-canonical type and non-numeric level values; Phase 3 ingestion should either repair those rows from a better CSV export or fail clearly with row-level diagnostics.
- If future CSV exports change column names or type/level formatting, the ingestion code should fail with a clear validation error.
"@

Set-Content -LiteralPath $OutPath -Value $report -Encoding UTF8
Write-Output "Wrote $OutPath"
