param(
  [string]$LogoPath = "public/brand/tournament-logo.png",
  [string]$WebLogoPath = "public/brand/tournament-logo-web.png",
  [string]$RuntimeCatalogPath = "data/generated/charts-with-images.json",
  [string]$ImageAssetManifestPath = "data/generated/image-assets.json",
  [string]$PublicCachePath = "public/chart-images/cache",
  [string]$OutPath = "docs/asset-audit.md"
)

$ErrorActionPreference = "Stop"

function Get-ImageAudit {
  param([string]$Path)

  $info = [ordered]@{
    Path = $Path
    Exists = Test-Path -LiteralPath $Path
    FileSize = 0
    SizeMb = 0
    Width = $null
    Height = $null
    Usable = "FAIL"
  }

  if ($info.Exists) {
    $item = Get-Item -LiteralPath $Path
    $info.FileSize = $item.Length
    $info.SizeMb = [math]::Round($item.Length / 1MB, 2)

    Add-Type -AssemblyName System.Drawing
    $image = [System.Drawing.Image]::FromFile($item.FullName)
    try {
      $info.Width = $image.Width
      $info.Height = $image.Height
    } finally {
      $image.Dispose()
    }

    if ($info.Width -gt 0 -and $info.Height -gt 0 -and $info.FileSize -gt 0) {
      $info.Usable = "PASS"
    }
  }

  return [pscustomobject]$info
}

function Format-Dimensions {
  param($Info)

  if ($Info.Exists) {
    return "$($Info.Width)x$($Info.Height)"
  }

  return "not available"
}

$source = Get-ImageAudit -Path $LogoPath
$web = Get-ImageAudit -Path $WebLogoPath
$runtimeCatalogExists = Test-Path -LiteralPath $RuntimeCatalogPath
$imageAssetManifestExists = Test-Path -LiteralPath $ImageAssetManifestPath
$runtimeCatalogSha = if ($runtimeCatalogExists) {
  (Get-FileHash -Algorithm SHA256 -LiteralPath $RuntimeCatalogPath).Hash
} else {
  "TODO"
}
$imageAssetManifestSha = if ($imageAssetManifestExists) {
  (Get-FileHash -Algorithm SHA256 -LiteralPath $ImageAssetManifestPath).Hash
} else {
  "TODO"
}
$runtimeChartCount = "TODO"

if ($runtimeCatalogExists) {
  $runtimeChartCount = (Get-Content -Raw -LiteralPath $RuntimeCatalogPath | ConvertFrom-Json).Count
}

$publicCacheFiles = @()

if (Test-Path -LiteralPath $PublicCachePath) {
  $publicCacheFiles = @(Get-ChildItem -LiteralPath $PublicCachePath -Filter "*.png" -File)
}

$publicCacheCount = $publicCacheFiles.Count
$publicCacheTotalBytes = 0
$publicCacheLargestBytes = 0

if ($publicCacheCount -gt 0) {
  $publicCacheTotalBytes = ($publicCacheFiles | Measure-Object -Property Length -Sum).Sum
  $publicCacheLargestBytes = ($publicCacheFiles | Measure-Object -Property Length -Maximum).Maximum
}

$publicCacheTotalMb = [math]::Round($publicCacheTotalBytes / 1MB, 2)
$publicCacheLargestKb = [math]::Round($publicCacheLargestBytes / 1KB, 1)
$recommendations = @()

if (-not $source.Exists) {
  $recommendations += "Add the tournament logo at the required stable path before release."
} else {
  $recommendations += "Keep the source logo at the required stable path for archive/source-of-truth purposes."
}

if (-not $web.Exists) {
  $recommendations += "Create an optimized web rendition for routine phone and stage route rendering."
} else {
  $recommendations += "Use the optimized web rendition for routine app rendering."
}

if ($source.FileSize -gt 10485760) {
  $recommendations += "Avoid loading the full-resolution source PNG directly on phones."
}

if ($web.Exists -and $web.FileSize -gt 1048576) {
  $recommendations += "Consider reducing the optimized logo rendition below 1 MB before release."
}

$recommendationLines = $recommendations | ForEach-Object { "- $_" }

$report = @"
# Asset Audit

Generated by `scripts/write-asset-audit.ps1`.

## Tournament Logo Source

- Path: $($source.Path)
- Exists: $(if ($source.Exists) { "PASS" } else { "FAIL" })
- Dimensions: $(Format-Dimensions -Info $source)
- File size: $($source.FileSize) bytes ($($source.SizeMb) MB)
- Usable as source tournament logo: $($source.Usable)

## Tournament Logo Web Rendition

- Path: $($web.Path)
- Exists: $(if ($web.Exists) { "PASS" } else { "FAIL" })
- Dimensions: $(Format-Dimensions -Info $web)
- File size: $($web.FileSize) bytes ($($web.SizeMb) MB)
- Usable as optimized app logo: $($web.Usable)

## Display Handling

$($recommendationLines -join "`n")

## Phase 11 Runtime Image Evidence Placeholders

Fill these values for the current release commit before tournament use.

- Runtime catalog source reported by npm run verify:real-chart-images: $(if ($runtimeCatalogExists) { $RuntimeCatalogPath } else { "TODO" })
- Runtime catalog SHA-256: $runtimeCatalogSha
- Image asset manifest SHA-256 for data/generated/image-assets.json: $imageAssetManifestSha
- Public cache file count verified against runtime catalog: $publicCacheCount PNG files
- Runtime charts with non-fallback cached artwork: $runtimeChartCount
- Total public cache size: $publicCacheTotalBytes bytes ($publicCacheTotalMb MB)
- Largest public cache file size: $publicCacheLargestBytes bytes ($publicCacheLargestKb KB)
- Verification command/date/commit: npm run verify:real-chart-images / TODO date / TODO commit
- Combined release data gate: npm run verify:release-data / TODO date / TODO commit

npm run verify:real-chart-images must validate the same runtime catalog source and public
cache paths that the deployed app uses, not only generated image metadata. npm run
verify:release-data must pass before release closure so the image manifest/runtime catalog hashes are
tied to the import report and source CSV evidence.

## Phase 11 Logo And Chart-Art Route Evidence Placeholders

The checked-in source logo is retained at the required path. The app should render the optimized
web rendition during normal event use.

- Approved optimized logo rendition path, if different from source: $($web.Path)
- Phone route logo bytes transferred on /room or /vote: TODO
- Projector route logo bytes transferred on /stage: TODO
- Deployed image request/resource evidence artifact: TODO
- Proof no chart art uses live third-party `bg_img` URLs: TODO
- Phone route manual/browser evidence date and viewport/device: TODO
- Projector route manual/browser evidence date and viewport: TODO
- Current release commit: TODO

Target: phone and projector routes should not require downloading the source PNG during normal
event use. Record the actual route evidence in docs/release-checklist.md before release.
"@

Set-Content -LiteralPath $OutPath -Value $report -Encoding UTF8
Write-Output "Wrote $OutPath"
