param(
  [string]$LogoPath = "public/brand/tournament-logo.png",
  [string]$OutPath = "docs/asset-audit.md"
)

$ErrorActionPreference = "Stop"

$exists = Test-Path -LiteralPath $LogoPath
$fileSize = 0
$width = $null
$height = $null
$usable = "FAIL"
$recommendations = @()

if ($exists) {
  $item = Get-Item -LiteralPath $LogoPath
  $fileSize = $item.Length
  Add-Type -AssemblyName System.Drawing
  $image = [System.Drawing.Image]::FromFile($item.FullName)
  try {
    $width = $image.Width
    $height = $image.Height
  } finally {
    $image.Dispose()
  }

  if ($width -gt 0 -and $height -gt 0 -and $fileSize -gt 0) {
    $usable = "PASS"
  }

  if ($fileSize -gt 10485760) {
    $recommendations += "Create optimized web renditions during Phase 1 or Phase 3; the source PNG is large for routine page loads."
  }
  if ($width -gt 2500) {
    $recommendations += "Use responsive image sizing and avoid loading the full-resolution asset on phones."
  }
  $recommendations += "Keep this file as the stable source brand asset unless a smaller approved source is provided."
  $recommendations += "Render it on stage/admin/player layouts where appropriate."
} else {
  $recommendations += "Add the tournament logo at the required stable path before Phase 1."
}

$sizeMb = [math]::Round($fileSize / 1MB, 2)
$dimensionsText = if ($exists) { "${width}x${height}" } else { "not available" }
$recommendationLines = $recommendations | ForEach-Object { "- $_" }

$report = @"
# Asset Audit

Generated by `scripts/write-asset-audit.ps1`.

## Tournament Logo

- Path: $LogoPath
- Exists: $(if ($exists) { "PASS" } else { "FAIL" })
- Dimensions: $dimensionsText
- File size: $fileSize bytes ($sizeMb MB)
- Usable as main tournament logo: $usable

## Recommendations for Phase 1 Display Handling

$($recommendationLines -join "`n")
"@

Set-Content -LiteralPath $OutPath -Value $report -Encoding UTF8
Write-Output "Wrote $OutPath"
