export const ADMIN_ACTION_POLICY_CLASSIFICATIONS = [
  "password-required dangerous action",
  "active-host-only tournament action",
  "read-only or sensitive disclosure action",
] as const;

export type AdminActionPolicyClassification =
  (typeof ADMIN_ACTION_POLICY_CLASSIFICATIONS)[number];

export type AdminActionPolicy = {
  serverAction: string;
  classification: AdminActionPolicyClassification;
  requiresAdminSession: boolean;
  requiresActiveHost: boolean;
  requiresPasswordReentry: boolean;
  requiresAuditReason: boolean;
  audited: boolean;
  dangerousAudit: boolean;
  tournamentChanging: boolean;
  rationale: string;
  conditionalDangerousVariant?: {
    when: string;
    requiresPasswordReentry: boolean;
    requiresAuditReason: boolean;
    dangerousAudit: boolean;
    rationale: string;
  };
};

export const ADMIN_ACTION_POLICIES = [
  {
    serverAction: "adminLoginAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: false,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: false,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale: "Creates only an admin session after the shared login password is accepted.",
  },
  {
    serverAction: "adminLogoutAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: false,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: false,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale:
      "Best-effort releases host control, then clears local admin and host cookies without changing tournament state.",
  },
  {
    serverAction: "expireAdminSessionAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: false,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: false,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale:
      "Best-effort inactivity cleanup releases host control before clearing expired admin cookies.",
  },
  {
    serverAction: "refreshAdminSessionAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: true,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: false,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale: "Refreshes an existing admin session and does not change tournament state.",
  },
  {
    serverAction: "takeHostControlAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: true,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale: "Normal host acquisition is operational lock management, not a tournament mutation.",
    conditionalDangerousVariant: {
      when: "forceHostTakeover=true",
      requiresPasswordReentry: true,
      requiresAuditReason: true,
      dangerousAudit: true,
      rationale: "Forced takeover can interrupt another active host and therefore needs re-entry.",
    },
  },
  {
    serverAction: "refreshHostLockAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: false,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: false,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale: "Heartbeat-only lock maintenance; frequent enough that audit rows would be noise.",
  },
  {
    serverAction: "releaseHostControlAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: true,
    requiresActiveHost: false,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale: "Releases or no-ops host control and records the outcome.",
  },
  {
    serverAction: "addPlayerAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine roster setup must be host-controlled and audited.",
  },
  {
    serverAction: "bulkImportPlayersAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine roster import must be host-controlled and audited.",
  },
  {
    serverAction: "setPlayerActiveStatusAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine active/inactive roster changes apply through host control and audit.",
  },
  {
    serverAction: "editPlayerUsernameAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Username correction is host-controlled and audited before tournament history exists.",
  },
  {
    serverAction: "updateChartExclusionAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Chart exclusion changes alter draw eligibility and need password re-entry.",
  },
  {
    serverAction: "addInactivePlayerToCurrentRoundAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Emergency current-round eligibility changes are explicitly dangerous.",
  },
  {
    serverAction: "drawRoundSetAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Initial server-side draw is a routine host operation with audit.",
  },
  {
    serverAction: "rerollOneChartAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Replacing one drawn chart is explicitly dangerous.",
  },
  {
    serverAction: "rerollRoundSetAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Rerolling a set is explicitly dangerous.",
  },
  {
    serverAction: "rerollFullRoundAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Rerolling a full round is explicitly dangerous.",
  },
  {
    serverAction: "openVotingAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine voting-window control remains active-host plus audit.",
  },
  {
    serverAction: "pauseVotingAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine voting-window control remains active-host plus audit.",
  },
  {
    serverAction: "resumeVotingAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine voting-window control remains active-host plus audit.",
  },
  {
    serverAction: "closeVotingAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Routine voting-window control remains active-host plus audit.",
  },
  {
    serverAction: "manualBallotAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Manual ballot entry and overwrite are explicitly dangerous.",
  },
  {
    serverAction: "computeResultsAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Computing results is server-authoritative but routine host-controlled work.",
  },
  {
    serverAction: "advanceResultRevealAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Reveal advancement is routine host-controlled stage operation.",
  },
  {
    serverAction: "downloadPrivateCsvAction",
    classification: "read-only or sensitive disclosure action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: false,
    rationale: "Private CSV export discloses admin-only data but does not change results.",
  },
  {
    serverAction: "downloadDebugSnapshotAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: false,
    rationale: "Debug snapshot export discloses sensitive operational state.",
  },
  {
    serverAction: "setCurrentRoundAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Current-round navigation is host-controlled and audited.",
  },
  {
    serverAction: "advanceCurrentRoundAction",
    classification: "active-host-only tournament action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: false,
    requiresAuditReason: false,
    audited: true,
    dangerousAudit: false,
    tournamentChanging: true,
    rationale: "Current-round advancement is host-controlled and audited.",
  },
  {
    serverAction: "startRehearsalModeAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Rehearsal setup resets operational data and is deployment-gated.",
  },
  {
    serverAction: "resetRehearsalModeAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Rehearsal reset clears operational data and is deployment-gated.",
  },
  {
    serverAction: "seedRehearsalTiebreakAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Rehearsal tiebreak seeding writes manual ballots and is deployment-gated.",
  },
  {
    serverAction: "reopenVotingAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Reopening voting is explicitly dangerous.",
  },
  {
    serverAction: "resetRoundAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Resetting a round is explicitly dangerous.",
  },
  {
    serverAction: "overrideResultAction",
    classification: "password-required dangerous action",
    requiresAdminSession: true,
    requiresActiveHost: true,
    requiresPasswordReentry: true,
    requiresAuditReason: true,
    audited: true,
    dangerousAudit: true,
    tournamentChanging: true,
    rationale: "Overriding a selected result is explicitly dangerous.",
  },
] as const satisfies readonly AdminActionPolicy[];
